[tasks.start]
description = "Start all services (Tailwind, Axum)"
run_task = { name = ["tw", "axum"], parallel = true }

[tasks.tw]
description = "Start Tailwind watcher"
script = "npm run dev"

[tasks.axum]
description = "Start Axum server"
script = "cargo watch -c -w src -x run"
